# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a29ad864a4a8a3079323bcce9d0855c389c269e79507af84f3861da852fc45cb98245fbaa3dc99e2753362c9650a9ac1d4aebab4b94f9fd68c9341daa41b6a76

test:
  secret_key_base: fc56494ef1a1086ca7536a5ce1dffb95ab839924c6573a32fa0e1f7bc0d4dce620bf076348f9d162ce073a224c36c179219517a28659e392c90eceb642213ba8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
